-- Predictive Maintenance: Database Setup
CREATE DATABASE IF NOT EXISTS MANUFACTURING_MAINTENANCE;

CREATE SCHEMA IF NOT EXISTS MANUFACTURING_MAINTENANCE.RAW;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_MAINTENANCE.CURATED;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_MAINTENANCE.AI;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_MAINTENANCE.ML;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_MAINTENANCE.SEARCH;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_MAINTENANCE.APP;

USE DATABASE MANUFACTURING_MAINTENANCE;
USE WAREHOUSE CORTEX;
