-- Predictive Maintenance: Raw Tables
USE SCHEMA MANUFACTURING_MAINTENANCE.RAW;

CREATE OR REPLACE TABLE EQUIPMENT (
    EQUIPMENT_ID VARCHAR,
    EQUIPMENT_NAME VARCHAR,
    EQUIPMENT_TYPE VARCHAR,
    MANUFACTURER VARCHAR,
    INSTALL_DATE DATE,
    LAST_SERVICE_DATE DATE,
    LOCATION VARCHAR,
    CRITICALITY VARCHAR,
    STATUS VARCHAR,
    VIBRATION_THRESHOLD NUMBER(5,2),
    TEMPERATURE_THRESHOLD NUMBER(5,2),
    PRESSURE_THRESHOLD NUMBER(5,2)
);

CREATE OR REPLACE TABLE SENSOR_READINGS (
    READING_ID VARCHAR,
    EQUIPMENT_ID VARCHAR,
    TIMESTAMP TIMESTAMP,
    VIBRATION_MM_S NUMBER(6,3),
    TEMPERATURE_C NUMBER(6,2),
    PRESSURE_BAR NUMBER(6,2),
    CURRENT_A NUMBER(6,2),
    OPERATIONAL_HOURS NUMBER
);

CREATE OR REPLACE TABLE WORK_ORDERS (
    WO_ID VARCHAR,
    EQUIPMENT_ID VARCHAR,
    WO_TYPE VARCHAR,           -- PREVENTIVE, CORRECTIVE, EMERGENCY, INSPECTION
    PRIORITY VARCHAR,
    CREATED_DATE TIMESTAMP,
    SCHEDULED_DATE TIMESTAMP,
    COMPLETED_DATE TIMESTAMP,
    STATUS VARCHAR,
    COST NUMBER(10,2),
    DESCRIPTION VARCHAR,
    ROOT_CAUSE VARCHAR
);

CREATE OR REPLACE TABLE FAILURE_HISTORY (
    FAILURE_ID VARCHAR,
    EQUIPMENT_ID VARCHAR,
    FAILURE_DATE TIMESTAMP,
    FAILURE_TYPE VARCHAR,
    ROOT_CAUSE VARCHAR,
    DOWNTIME_HOURS NUMBER,
    REPAIR_COST NUMBER(12,2),
    PRODUCTION_LOSS NUMBER(12,2),
    TOTAL_IMPACT NUMBER(12,2),
    DESCRIPTION VARCHAR
);

CREATE OR REPLACE TABLE MAINTENANCE_DOCS (
    DOC_ID VARCHAR,
    TITLE VARCHAR,
    CATEGORY VARCHAR,
    EQUIPMENT_TYPE VARCHAR,
    CONTENT VARCHAR,
    LAST_UPDATED TIMESTAMP
);
