-- Predictive Maintenance: External Stage & Data Loading
USE SCHEMA MANUFACTURING_MAINTENANCE.RAW;

CREATE OR REPLACE STAGE MAINTENANCE_S3_STAGE
    URL = 's3://sg-manufacturing-demos-2026/maintenance/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO EQUIPMENT FROM @MAINTENANCE_S3_STAGE/equipment/;
COPY INTO SENSOR_READINGS FROM @MAINTENANCE_S3_STAGE/sensor_readings/;
COPY INTO WORK_ORDERS FROM @MAINTENANCE_S3_STAGE/work_orders/;
COPY INTO FAILURE_HISTORY FROM @MAINTENANCE_S3_STAGE/failure_history/;
COPY INTO MAINTENANCE_DOCS FROM @MAINTENANCE_S3_STAGE/maintenance_docs/;
