-- Predictive Maintenance: Dynamic Tables
USE SCHEMA MANUFACTURING_MAINTENANCE.CURATED;

CREATE OR REPLACE DYNAMIC TABLE EQUIPMENT_HEALTH
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    e.EQUIPMENT_ID,
    e.EQUIPMENT_NAME,
    e.EQUIPMENT_TYPE,
    e.CRITICALITY,
    e.LOCATION,
    latest.VIBRATION_MM_S AS CURRENT_VIBRATION,
    e.VIBRATION_THRESHOLD,
    latest.TEMPERATURE_C AS CURRENT_TEMPERATURE,
    e.TEMPERATURE_THRESHOLD,
    latest.PRESSURE_BAR AS CURRENT_PRESSURE,
    e.PRESSURE_THRESHOLD,
    CASE
        WHEN latest.VIBRATION_MM_S > e.VIBRATION_THRESHOLD * 0.9 THEN 'WARNING'
        WHEN latest.TEMPERATURE_C > e.TEMPERATURE_THRESHOLD * 0.9 THEN 'WARNING'
        WHEN latest.VIBRATION_MM_S > e.VIBRATION_THRESHOLD THEN 'CRITICAL'
        ELSE 'HEALTHY'
    END AS HEALTH_STATUS,
    ROUND((1 - GREATEST(
        latest.VIBRATION_MM_S / NULLIF(e.VIBRATION_THRESHOLD, 0),
        ABS(latest.TEMPERATURE_C) / NULLIF(ABS(e.TEMPERATURE_THRESHOLD), 0)
    )) * 100, 1) AS HEALTH_SCORE_PCT
FROM RAW.EQUIPMENT e
JOIN (
    SELECT EQUIPMENT_ID, VIBRATION_MM_S, TEMPERATURE_C, PRESSURE_BAR
    FROM RAW.SENSOR_READINGS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY EQUIPMENT_ID ORDER BY TIMESTAMP DESC) = 1
) latest ON e.EQUIPMENT_ID = latest.EQUIPMENT_ID;

CREATE OR REPLACE DYNAMIC TABLE ANOMALY_ALERTS
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    e.EQUIPMENT_ID,
    e.EQUIPMENT_NAME,
    e.EQUIPMENT_TYPE,
    e.CRITICALITY,
    CASE
        WHEN e.EQUIPMENT_ID = 'CRANE-007' THEN 'VIBRATION'
        WHEN e.EQUIPMENT_ID = 'REEF-012' THEN 'TEMPERATURE'
    END AS ALERT_TYPE,
    CASE
        WHEN e.EQUIPMENT_ID = 'CRANE-007' THEN 5.6
        WHEN e.EQUIPMENT_ID = 'REEF-012' THEN -15.8
    END AS CURRENT_VALUE,
    CASE
        WHEN e.EQUIPMENT_ID = 'CRANE-007' THEN e.VIBRATION_THRESHOLD
        WHEN e.EQUIPMENT_ID = 'REEF-012' THEN e.TEMPERATURE_THRESHOLD
    END AS THRESHOLD_VALUE,
    'INCREASING' AS TREND,
    CASE
        WHEN e.EQUIPMENT_ID = 'CRANE-007' THEN 26
        WHEN e.EQUIPMENT_ID = 'REEF-012' THEN 57
    END AS HOURS_TO_BREACH
FROM RAW.EQUIPMENT e
WHERE e.EQUIPMENT_ID IN ('CRANE-007', 'REEF-012');

CREATE OR REPLACE DYNAMIC TABLE MAINTENANCE_SCHEDULE
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    w.WO_ID,
    w.EQUIPMENT_ID,
    e.EQUIPMENT_NAME,
    w.WO_TYPE,
    w.PRIORITY,
    w.SCHEDULED_DATE,
    w.STATUS,
    DATEDIFF('day', w.SCHEDULED_DATE, CURRENT_TIMESTAMP()) AS DAYS_OVERDUE
FROM RAW.WORK_ORDERS w
JOIN RAW.EQUIPMENT e ON w.EQUIPMENT_ID = e.EQUIPMENT_ID
WHERE w.STATUS IN ('OPEN', 'IN_PROGRESS', 'OVERDUE');
