-- Predictive Maintenance: Cortex Search
-- Enhanced with 416 docs: Machine Manuals, Technician Field Notes, Safety Bulletins, Spare Parts
USE SCHEMA MANUFACTURING_MAINTENANCE.SEARCH;

CREATE OR REPLACE CORTEX SEARCH SERVICE MAINTENANCE_DOCS_SEARCH
    ON CONTENT
    ATTRIBUTES CATEGORY, EQUIPMENT_TYPE, EQUIPMENT_ID, AUTHOR, SEVERITY
    WAREHOUSE = CORTEX
    TARGET_LAG = '1 hour'
    EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS (
    SELECT DOC_ID, TITLE, CATEGORY, EQUIPMENT_TYPE, EQUIPMENT_ID,
           AUTHOR, DOC_DATE::STRING AS DOC_DATE, SEVERITY, PART_NUMBER, CONTENT
    FROM RAW.MAINTENANCE_DOCS
);
