-- Predictive Maintenance: Cortex Search
USE SCHEMA MANUFACTURING_MAINTENANCE.SEARCH;

CREATE OR REPLACE CORTEX SEARCH SERVICE MAINTENANCE_DOCS_SEARCH
    ON (
        SELECT DOC_ID, TITLE, CATEGORY, EQUIPMENT_TYPE, CONTENT
        FROM RAW.MAINTENANCE_DOCS
    )
    WAREHOUSE = CORTEX
    TARGET_LAG = '1 hour'
    EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
    AS (
        SEARCH_COLUMN => 'CONTENT',
        COLUMNS => ['DOC_ID', 'TITLE', 'CATEGORY', 'EQUIPMENT_TYPE', 'CONTENT']
    );
