-- Predictive Maintenance: ML Models
USE SCHEMA MANUFACTURING_MAINTENANCE.ML;

CREATE OR REPLACE VIEW SENSOR_ANOMALY_INPUT AS
SELECT
    DATE_TRUNC('hour', s.TIMESTAMP) AS DS,
    s.EQUIPMENT_ID AS SERIES,
    AVG(s.VIBRATION_MM_S) AS Y
FROM RAW.SENSOR_READINGS s
GROUP BY DS, SERIES;

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION SENSOR_ANOMALY_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'SENSOR_ANOMALY_INPUT'),
    SERIES_COLNAME => 'SERIES',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);
