-- ============================================================================
-- 10_iot_sitewise.sql
-- Expanded IoT SiteWise asset model: Plant -> Line -> Equipment hierarchy
-- ============================================================================
-- Architecture:
--   AWS IoT SiteWise model `mfg-maintenance-cranes` has 100+ assets
--   This script mirrors the hierarchy in Snowflake for analytics
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS MANUFACTURING_MAINTENANCE.SITEWISE;

CREATE OR REPLACE TABLE MANUFACTURING_MAINTENANCE.SITEWISE.PLANT_HIERARCHY (
    PLANT_NAME VARCHAR,
    PRODUCTION_LINE VARCHAR,
    EQUIPMENT_ID VARCHAR,
    EQUIPMENT_TYPE VARCHAR,
    SITEWISE_ASSET_NAME VARCHAR,
    INSTALLED_DATE DATE
);

INSERT INTO MANUFACTURING_MAINTENANCE.SITEWISE.PLANT_HIERARCHY
WITH plants AS (
    SELECT 'Singapore Jurong' AS PLANT_NAME, 'Line-A1' AS LINE UNION ALL
    SELECT 'Singapore Jurong', 'Line-A2' UNION ALL
    SELECT 'Singapore Jurong', 'Line-A3' UNION ALL
    SELECT 'Singapore Tuas', 'Line-B1' UNION ALL
    SELECT 'Singapore Tuas', 'Line-B2' UNION ALL
    SELECT 'Singapore Tuas', 'Line-B3' UNION ALL
    SELECT 'Batam', 'Line-C1' UNION ALL
    SELECT 'Batam', 'Line-C2'
),
lines_numbered AS (
    SELECT PLANT_NAME, LINE, ROW_NUMBER() OVER (ORDER BY LINE) - 1 AS LINE_IDX
    FROM plants
),
equip AS (
    SELECT EQUIPMENT_ID, TYPE AS EQUIPMENT_TYPE, ROW_NUMBER() OVER (ORDER BY EQUIPMENT_ID) - 1 AS EQUIP_IDX
    FROM MANUFACTURING_MAINTENANCE.RAW.EQUIPMENT
)
SELECT
    l.PLANT_NAME,
    l.LINE AS PRODUCTION_LINE,
    e.EQUIPMENT_ID,
    e.EQUIPMENT_TYPE,
    e.EQUIPMENT_ID || '-' || REPLACE(e.EQUIPMENT_TYPE, '_', '-') AS SITEWISE_ASSET_NAME,
    DATEADD('day', -UNIFORM(365, 1825, RANDOM()), CURRENT_DATE()) AS INSTALLED_DATE
FROM equip e
JOIN lines_numbered l ON MOD(e.EQUIP_IDX, 8) = l.LINE_IDX;

CREATE OR REPLACE TABLE MANUFACTURING_MAINTENANCE.SITEWISE.PROPERTY_DEFINITIONS (
    PROPERTY_NAME VARCHAR,
    UNIT VARCHAR,
    DATA_TYPE VARCHAR,
    ALARM_LOW NUMBER(8,2),
    ALARM_HIGH NUMBER(8,2),
    DESCRIPTION VARCHAR
);

INSERT INTO MANUFACTURING_MAINTENANCE.SITEWISE.PROPERTY_DEFINITIONS VALUES
    ('vibration_mm_s', 'mm/s', 'DOUBLE', 0, 6.0, 'Bearing vibration velocity'),
    ('temperature_c', '°C', 'DOUBLE', -20, 85, 'Operating temperature'),
    ('oil_pressure_bar', 'bar', 'DOUBLE', 2, 12, 'Hydraulic/pneumatic pressure'),
    ('current_a', 'A', 'DOUBLE', 0, 50, 'Motor current draw'),
    ('operational_hours', 'hrs', 'INTEGER', 0, 50000, 'Cumulative run hours');

CREATE OR REPLACE VIEW MANUFACTURING_MAINTENANCE.SITEWISE.VW_ASSET_HEALTH AS
SELECT
    ph.PLANT_NAME,
    ph.PRODUCTION_LINE,
    ph.EQUIPMENT_ID,
    ph.EQUIPMENT_TYPE,
    ph.SITEWISE_ASSET_NAME,
    eh.NAME AS EQUIPMENT_NAME,
    eh.HEALTH_SCORE,
    eh.STATUS,
    eh.CRITICALITY,
    eh.CRITICAL_SENSORS,
    eh.WARNING_SENSORS,
    eh.LAST_MAINTENANCE
FROM MANUFACTURING_MAINTENANCE.SITEWISE.PLANT_HIERARCHY ph
JOIN MANUFACTURING_MAINTENANCE.CURATED.EQUIPMENT_HEALTH eh
    ON ph.EQUIPMENT_ID = eh.EQUIPMENT_ID;

TRUNCATE TABLE MANUFACTURING_MAINTENANCE.SITEWISE.ASSET_MODEL;
INSERT INTO MANUFACTURING_MAINTENANCE.SITEWISE.ASSET_MODEL
SELECT
    v.EQUIPMENT_ID AS ASSET_ID,
    v.EQUIPMENT_NAME AS ASSET_NAME,
    'mfg-maintenance/cranes' AS ASSET_MODEL_ID,
    v.PRODUCTION_LINE AS PARENT_ASSET,
    OBJECT_CONSTRUCT(
        'health_score', v.HEALTH_SCORE,
        'critical_sensors', v.CRITICAL_SENSORS,
        'warning_sensors', v.WARNING_SENSORS,
        'criticality', v.CRITICALITY,
        'plant', v.PLANT_NAME,
        'last_maintenance', v.LAST_MAINTENANCE::STRING
    ) AS PROPERTIES,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM MANUFACTURING_MAINTENANCE.SITEWISE.VW_ASSET_HEALTH v;

CREATE OR REPLACE VIEW MANUFACTURING_MAINTENANCE.SITEWISE.VW_SENSOR_ROLLUP AS
SELECT
    ph.PLANT_NAME,
    ph.PRODUCTION_LINE,
    am.ASSET_ID,
    am.ASSET_NAME,
    eh.HEALTH_SCORE,
    eh.CRITICAL_SENSORS,
    eh.WARNING_SENSORS,
    eh.STATUS,
    eh.CRITICALITY,
    aa.SENSOR_TYPE AS ANOMALY_TYPE,
    aa.TREND_DIRECTION AS SEVERITY,
    aa.CURRENT_VALUE AS SENSOR_VALUE,
    aa.THRESHOLD_HIGH AS THRESHOLD,
    aa.HOURS_TO_BREACH_ESTIMATE AS HOURS_TO_BREACH
FROM MANUFACTURING_MAINTENANCE.SITEWISE.ASSET_MODEL am
JOIN MANUFACTURING_MAINTENANCE.SITEWISE.PLANT_HIERARCHY ph ON am.ASSET_ID = ph.EQUIPMENT_ID
JOIN MANUFACTURING_MAINTENANCE.CURATED.EQUIPMENT_HEALTH eh ON am.ASSET_ID = eh.EQUIPMENT_ID
LEFT JOIN MANUFACTURING_MAINTENANCE.CURATED.ANOMALY_ALERTS aa ON aa.EQUIPMENT_ID = am.ASSET_ID;
