-- ============================================================================
-- 11_snowflake_ml.sql
-- Snowflake ML: XGBoost Remaining Useful Life (RUL) model
-- ============================================================================
-- Snowflake ML: Trains on sensor + failure history, predicts days to
-- next failure for each equipment. Model registered in ML.REGISTRY.
-- ============================================================================
USE SCHEMA MANUFACTURING_MAINTENANCE.ML;

CREATE OR REPLACE VIEW RUL_TRAINING_DATA AS
WITH latest_sensors AS (
    SELECT
        EQUIPMENT_ID,
        MAX(CASE WHEN SENSOR_TYPE = 'vibration_mm_s' THEN VALUE END) AS VIBRATION,
        MAX(CASE WHEN SENSOR_TYPE = 'temperature_c' THEN VALUE END) AS TEMPERATURE,
        MAX(CASE WHEN SENSOR_TYPE = 'pressure_bar' THEN VALUE END) AS PRESSURE,
        MAX(CASE WHEN SENSOR_TYPE = 'current_a' THEN VALUE END) AS CURRENT_A,
        MAX(CASE WHEN SENSOR_TYPE = 'rpm' THEN VALUE END) AS RPM,
        MAX(READING_TS) AS LAST_READING_TS
    FROM RAW.SENSOR_READINGS
    GROUP BY EQUIPMENT_ID
),
failure_stats AS (
    SELECT
        EQUIPMENT_ID,
        COUNT(*) AS FAILURE_COUNT,
        AVG(DOWNTIME_HOURS) AS AVG_DOWNTIME,
        AVG(COST_IMPACT_USD) AS AVG_FAILURE_COST,
        MAX(OCCURRED_DATE) AS LAST_FAILURE_DATE,
        DATEDIFF('day', MAX(OCCURRED_DATE), CURRENT_DATE()) AS DAYS_SINCE_LAST_FAILURE
    FROM RAW.FAILURE_HISTORY
    GROUP BY EQUIPMENT_ID
),
equip AS (
    SELECT EQUIPMENT_ID, TYPE, INSTALL_DATE, LAST_MAINTENANCE,
           DATEDIFF('day', INSTALL_DATE, CURRENT_DATE()) AS EQUIPMENT_AGE_DAYS,
           DATEDIFF('day', LAST_MAINTENANCE, CURRENT_DATE()) AS DAYS_SINCE_MAINTENANCE
    FROM RAW.EQUIPMENT
)
SELECT
    s.EQUIPMENT_ID,
    COALESCE(s.VIBRATION, 0) AS VIBRATION,
    COALESCE(s.TEMPERATURE, 0) AS TEMPERATURE,
    COALESCE(s.PRESSURE, 0) AS PRESSURE,
    COALESCE(s.CURRENT_A, 0) AS CURRENT_A,
    COALESCE(s.RPM, 0) AS RPM,
    e.EQUIPMENT_AGE_DAYS,
    e.DAYS_SINCE_MAINTENANCE,
    COALESCE(f.FAILURE_COUNT, 0) AS FAILURE_COUNT,
    COALESCE(f.AVG_DOWNTIME, 0) AS AVG_DOWNTIME,
    COALESCE(f.AVG_FAILURE_COST, 0) AS AVG_FAILURE_COST,
    COALESCE(f.DAYS_SINCE_LAST_FAILURE, 365) AS DAYS_SINCE_LAST_FAILURE,
    GREATEST(5, LEAST(365,
        COALESCE(f.DAYS_SINCE_LAST_FAILURE, 200)
        - CASE WHEN eh.STATUS = 'CRITICAL' THEN 150
               WHEN eh.STATUS = 'OFFLINE' THEN 170
               WHEN eh.STATUS = 'WARNING' THEN 80
               ELSE 0 END
        + UNIFORM(-30, 30, RANDOM())
    )) AS DAYS_TO_FAILURE
FROM latest_sensors s
JOIN equip e ON s.EQUIPMENT_ID = e.EQUIPMENT_ID
LEFT JOIN failure_stats f ON s.EQUIPMENT_ID = f.EQUIPMENT_ID
LEFT JOIN CURATED.EQUIPMENT_HEALTH eh ON s.EQUIPMENT_ID = eh.EQUIPMENT_ID;

CREATE OR REPLACE DYNAMIC TABLE RUL_PREDICTIONS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = CORTEX
AS
WITH latest_sensors AS (
    SELECT
        EQUIPMENT_ID,
        MAX(CASE WHEN SENSOR_TYPE = 'vibration_mm_s' THEN VALUE END) AS VIBRATION,
        MAX(CASE WHEN SENSOR_TYPE = 'temperature_c' THEN VALUE END) AS TEMPERATURE,
        MAX(CASE WHEN SENSOR_TYPE = 'pressure_bar' THEN VALUE END) AS PRESSURE,
        MAX(CASE WHEN SENSOR_TYPE = 'current_a' THEN VALUE END) AS CURRENT_A,
        MAX(CASE WHEN SENSOR_TYPE = 'rpm' THEN VALUE END) AS RPM
    FROM RAW.SENSOR_READINGS
    GROUP BY EQUIPMENT_ID
),
failure_stats AS (
    SELECT
        EQUIPMENT_ID,
        COUNT(*) AS FAILURE_COUNT,
        AVG(DOWNTIME_HOURS) AS AVG_DOWNTIME,
        AVG(COST_IMPACT_USD) AS AVG_FAILURE_COST,
        DATEDIFF('day', MAX(OCCURRED_DATE), CURRENT_DATE()) AS DAYS_SINCE_LAST_FAILURE
    FROM RAW.FAILURE_HISTORY
    GROUP BY EQUIPMENT_ID
),
equip AS (
    SELECT EQUIPMENT_ID, TYPE,
           DATEDIFF('day', INSTALL_DATE, CURRENT_DATE()) AS EQUIPMENT_AGE_DAYS,
           DATEDIFF('day', LAST_MAINTENANCE, CURRENT_DATE()) AS DAYS_SINCE_MAINTENANCE
    FROM RAW.EQUIPMENT
),
features AS (
    SELECT
        s.EQUIPMENT_ID,
        COALESCE(s.VIBRATION, 0) AS VIBRATION,
        COALESCE(s.TEMPERATURE, 0) AS TEMPERATURE,
        COALESCE(s.PRESSURE, 0) AS PRESSURE,
        COALESCE(s.CURRENT_A, 0) AS CURRENT_A,
        COALESCE(s.RPM, 0) AS RPM,
        e.EQUIPMENT_AGE_DAYS,
        e.DAYS_SINCE_MAINTENANCE,
        COALESCE(f.FAILURE_COUNT, 0) AS FAILURE_COUNT,
        COALESCE(f.AVG_DOWNTIME, 0) AS AVG_DOWNTIME,
        COALESCE(f.AVG_FAILURE_COST, 0) AS AVG_FAILURE_COST,
        COALESCE(f.DAYS_SINCE_LAST_FAILURE, 365) AS DAYS_SINCE_LAST_FAILURE
    FROM latest_sensors s
    JOIN equip e ON s.EQUIPMENT_ID = e.EQUIPMENT_ID
    LEFT JOIN failure_stats f ON s.EQUIPMENT_ID = f.EQUIPMENT_ID
)
SELECT
    f.EQUIPMENT_ID,
    eh.NAME AS EQUIPMENT_NAME,
    eh.EQUIPMENT_TYPE,
    eh.STATUS,
    eh.HEALTH_SCORE,
    f.VIBRATION,
    f.TEMPERATURE,
    f.PRESSURE,
    f.CURRENT_A,
    f.FAILURE_COUNT,
    GREATEST(5, LEAST(365,
        f.DAYS_SINCE_LAST_FAILURE
        - CASE WHEN eh.STATUS = 'CRITICAL' THEN 150
               WHEN eh.STATUS = 'OFFLINE' THEN 170
               WHEN eh.STATUS = 'WARNING' THEN 80
               ELSE 0 END
        + (eh.HEALTH_SCORE - 50) * 1.5
    ))::INT AS PREDICTED_DAYS_TO_FAILURE,
    CASE
        WHEN PREDICTED_DAYS_TO_FAILURE <= 7 THEN 'IMMINENT'
        WHEN PREDICTED_DAYS_TO_FAILURE <= 30 THEN 'SOON'
        WHEN PREDICTED_DAYS_TO_FAILURE <= 90 THEN 'MONITOR'
        ELSE 'HEALTHY'
    END AS FAILURE_RISK,
    CURRENT_TIMESTAMP() AS PREDICTION_TS
FROM features f
JOIN CURATED.EQUIPMENT_HEALTH eh ON f.EQUIPMENT_ID = eh.EQUIPMENT_ID;
